'''

@author: rtermondt
'''

RECORDS_PER_PAGE = 25

PROFILE_CREATE_EVENT = 'PROFILE_CREATE'
CONFIRM_ACCOUNT_SUBJECT = 'Please confirm account'

INVITATION_EVENT = 'INVITATION'
INTERNAL_INVITATION_REQUEST_SUBJECT = 'Invitation request'
INTERNAL_INVITATION_REQUEST_BODY = 'A new invitation request has been submitted.'

ACCOUNT_CONFIRMED_EVENT = 'ACCOUNT_CONFIRMED'
ACCOUNT_CONFIRMED_SUBJECT = 'Account confirmed'

ACCESS_REQUEST_APPROVED_EVENT = 'ACCESS_APPROVED'
ACCESS_REQUEST_APPROVED_SUBJECT = 'Access request approved'

USER_INVITE_EVENT = 'USER_INVITE'
USER_INVITE_SUBJECT = 'Your invitation to InitHub'

SUPPORT_TICKET_NEW_EVENT = 'NEW_SUPPORT_TICKET'
SUPPORT_TICKET_REPLY = 'SUPPORT_REPLY'
SUPPORT_TICKET_CUSTOMER_REPLY = 'SUPPORT_CUSTOMER_REPLY'

INITIATIVE_LAUNCH = 'INITIATIVE_LAUNCH'
